version: '3'

services:
      
  platformweb:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  platformdb:
    image: postgres
    env_file:
      - .env.database
    volumes:
      - db-platform:/var/lib/postgresql/data

volumes:
  db-platform:
