version: "3.5"

services:
  platformweb:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # rails server (Guardfile, config/environments/development.rb)
      - "3020:3020"
      # webpack-dev-server (config/webpacker.yml)
      - "3035:3035"
      # rack-livereload (config/environments/development.rb)
      - "35729:35729"
      # rspec server host port. The web server that rspec listens on when running tests. http://SPEC_HOST:SPEC_PORT
      - "49883:49883"
    volumes:
      - .:/usr/src/app
      - node-modules:/usr/src/app/node_modules
      - /usr/src/app/tmp
      - /usr/src/app/log
    depends_on:
      - platform_chrome
      - platformdb
    env_file:
      - .env
    # These take precedence over any values in the above file.
    # Set them in your shell before using docker-compose so they get passed in.
    environment:
      SALESFORCE_PLATFORM_CONSUMER_KEY: ${SALESFORCE_PLATFORM_CONSUMER_KEY}
      SALESFORCE_PLATFORM_CONSUMER_SECRET: ${SALESFORCE_PLATFORM_CONSUMER_SECRET}
      SALESFORCE_PLATFORM_USERNAME: ${SALESFORCE_PLATFORM_USERNAME}
      SALESFORCE_PLATFORM_PASSWORD: ${SALESFORCE_PLATFORM_PASSWORD}
      SALESFORCE_PLATFORM_SECURITY_TOKEN: ${SALESFORCE_PLATFORM_SECURITY_TOKEN}
    
    networks:
      - bravendev
    # Note: there are some issues with the listen gem and certain editors
    # where gaurd won't detect changes made from the host machine on a Mac
    # inside the container when the volume is mounted. For VIM, you need to add
    #   set backupcopy=yes 
    # in your .vimrc
    # See: https://github.com/guard/listen/issues/434
    # Also, if you force polling it will absolutely destroy your CPU.
    command: bundle exec guard -di

  platformdb:
    image: postgres
    env_file:
      - .env.database
    volumes:
      - db-platform:/var/lib/postgresql/data
    networks:
      - bravendev

  platform_chrome:
    image: selenium/standalone-chrome
    # SELENIUM_PORT
    ports: ['4444:4444']
    # remote debugging port
    ports: ['9222:9222']
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - bravendev
    # Disable noisy logs.
    #logging:
    #  driver: none

volumes:
  db-platform:
  node-modules:

# Note all Braven web app docker dev envs use this same network so they can talk to each other.
# E.g. the hostname joinweb will resolve inside the ssoweb container if they are on the same docker network.
networks:
  bravendev:
    name: braven_dev_network
