version: "3.5"

services:
  platformweb:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # rails server (Guardfile, config/environments/development.rb)
      - "3020:3020"
      # webpack-dev-server (config/webpacker.yml)
      - "3035:3035"
      # rack-livereload (config/environments/development.rb)
      - "35729:35729"
    volumes:
      - .:/usr/src/app
      - node-modules:/usr/src/app/node_modules
      - /usr/src/app/tmp
      - /usr/src/app/log
    env_file:
      - .env
    networks:
      - bravendev
    # Note: there are some issues with the listen gem and certain editors
    # where gaurd won't detect changes made from the host machine on a Mac
    # inside the container when the volume is mounted. For VIM, you need to add
    #   set backupcopy=yes 
    # in your .vimrc
    # See: https://github.com/guard/listen/issues/434
    # Also, if you force polling it will absolutely destroy your CPU.
    command: bundle exec guard -di

  platformdb:
    image: postgres
    env_file:
      - .env.database
    volumes:
      - db-platform:/var/lib/postgresql/data
    networks:
      - bravendev

volumes:
  db-platform:
  node-modules:

# Note all Braven web app docker dev envs use this same network so they can talk to each other.
# E.g. the hostname joinweb will resolve inside the ssoweb container if they are on the same docker network.
networks:
  bravendev:
    name: braven_dev_network
