version: '3'

services:
      
  data-central:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env

  database:
    image: postgres
    env_file:
      - .env.database
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  gem_cache: