development:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>

test:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>

staging:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>

production:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>

