development:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  
test:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  
staging:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  
production:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>